#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/lib.sh

[[ -n "$DEBUG" ]] && set -x

if ! declare -f $1 > /dev/null; then
  _tabs
  if [[ $1 == 'help' && -n "$2" ]]; then

    type $2 || echo ${!2}
  else

    tabs 1,2,+6,+14,+18,+5,+5
    headline 1 variables
    define | sed s'/^/\t\t/g'

    headline 1 functions
    for i in $(declare -F | sed s/'declare -f//g' | sort); do
      [[ "${_doc[$i]}" =~ (internal|deprecated) ]] || printf "\t\t%s\t %s\n" $i "${_doc[$i]}"
    done
  fi
  exit 1
fi
fn=$1
shift
tabs -8

$fn "$@"
